# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
